import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

interface MaintenanceJobData {
  name: string
  category: string
  parts?: string
  notes?: string
}

const maintenanceJobs: MaintenanceJobData[] = [
  // Engine & Drivetrain
  { name: 'Engine oil change', category: 'Engine', notes: 'Every 5,000-10,000 km or 6 months' },
  { name: 'Oil filter replacement', category: 'Engine', notes: 'Replace with oil change' },
  { name: 'Fuel filter replacement', category: 'Engine', notes: 'Every 20,000-40,000 km' },
  { name: 'Air filter replacement', category: 'Engine', notes: 'Every 15,000-30,000 km' },
  { name: 'Cabin air filter replacement', category: 'Engine', notes: 'Every 20,000 km or annually' },
  { name: 'Coolant flush & replacement', category: 'Cooling', notes: 'Every 40,000-60,000 km or 2 years' },
  { name: 'Radiator inspection', category: 'Cooling', notes: 'Check for leaks and damage' },
  { name: 'Radiator leak repair', category: 'Cooling', notes: 'Repair leaks as needed' },
  { name: 'Radiator replacement', category: 'Cooling', notes: 'Replace if damaged beyond repair' },
  { name: 'Radiator cap replacement', category: 'Cooling', notes: 'Replace if pressure seal fails' },
  { name: 'Thermostat inspection', category: 'Cooling', notes: 'Check proper operation' },
  { name: 'Thermostat replacement', category: 'Cooling', notes: 'Replace if stuck open/closed' },
  { name: 'Water pump inspection', category: 'Cooling', notes: 'Check for leaks and bearing wear' },
  { name: 'Water pump replacement', category: 'Cooling', notes: 'Replace if leaking or noisy' },
  { name: 'Serpentine/fan belt inspection', category: 'Engine', notes: 'Check for cracks and wear' },
  { name: 'Serpentine/fan belt replacement', category: 'Engine', notes: 'Every 80,000-100,000 km' },
  { name: 'Belt tensioner inspection', category: 'Engine', notes: 'Check proper tension and operation' },
  { name: 'Belt tensioner replacement', category: 'Engine', notes: 'Replace if worn or noisy' },
  { name: 'Turbocharger inspection', category: 'Engine', notes: 'Check for proper operation and leaks' },
  { name: 'Turbocharger cleaning', category: 'Engine', notes: 'Clean carbon deposits' },
  { name: 'Turbocharger replacement', category: 'Engine', notes: 'Replace if failed' },
  { name: 'Turbo oil line cleaning', category: 'Engine', notes: 'Clean oil supply lines' },
  { name: 'Turbo oil line replacement', category: 'Engine', notes: 'Replace if clogged or damaged' },
  { name: 'EGR valve inspection', category: 'Engine', notes: 'Check for carbon buildup' },
  { name: 'EGR valve cleaning', category: 'Engine', notes: 'Clean carbon deposits' },
  { name: 'EGR valve replacement', category: 'Engine', notes: 'Replace if faulty' },
  { name: 'Intercooler inspection', category: 'Engine', notes: 'Check for leaks and damage' },
  { name: 'Intercooler cleaning', category: 'Engine', notes: 'Clean internal passages' },
  { name: 'Intercooler hose replacement', category: 'Engine', notes: 'Replace if cracked or leaking' },
  { name: 'Fuel injector inspection', category: 'Engine', notes: 'Check spray pattern and operation' },
  { name: 'Fuel injector cleaning', category: 'Engine', notes: 'Ultrasonic cleaning' },
  { name: 'Fuel injector replacement', category: 'Engine', notes: 'Replace if faulty' },
  { name: 'Injection pump calibration', category: 'Engine', notes: 'Calibrate fuel delivery' },
  { name: 'Cylinder head inspection', category: 'Engine', notes: 'Check for cracks and warping' },
  { name: 'Cylinder head resurfacing', category: 'Engine', notes: 'Machine head surface flat' },
  { name: 'Cylinder head gasket replacement', category: 'Engine', notes: 'Replace if blown' },
  { name: 'Valve clearance adjustment', category: 'Engine', notes: 'Adjust valve lash' },
  { name: 'Valve cover gasket replacement', category: 'Engine', notes: 'Replace if leaking oil' },
  { name: 'Glow plug inspection', category: 'Engine', notes: 'Check resistance and operation' },
  { name: 'Glow plug replacement', category: 'Engine', notes: 'Replace if faulty' },
  { name: 'Spark plug inspection (for petrol engines)', category: 'Engine', notes: 'Check gap and condition' },
  { name: 'Spark plug replacement', category: 'Engine', notes: 'Every 30,000-50,000 km' },
  { name: 'Timing belt inspection', category: 'Engine', notes: 'Check for wear and cracks' },
  { name: 'Timing belt replacement', category: 'Engine', notes: 'Every 80,000-100,000 km' },
  { name: 'Timing chain inspection', category: 'Engine', notes: 'Check for stretch and wear' },
  { name: 'Timing chain replacement', category: 'Engine', notes: 'Replace if stretched or noisy' },
  { name: 'Camshaft inspection', category: 'Engine', notes: 'Check for wear and damage' },
  { name: 'Camshaft bearing replacement', category: 'Engine', notes: 'Replace if worn' },
  { name: 'Crankshaft inspection', category: 'Engine', notes: 'Check for wear and damage' },
  { name: 'Crankshaft seal replacement', category: 'Engine', notes: 'Replace if leaking' },
  { name: 'Engine mount inspection', category: 'Engine', notes: 'Check for cracks and wear' },
  { name: 'Engine mount replacement', category: 'Engine', notes: 'Replace if broken or worn' },
  { name: 'Oil sump inspection', category: 'Engine', notes: 'Check for damage and leaks' },
  { name: 'Oil sump gasket replacement', category: 'Engine', notes: 'Replace if leaking' },
  { name: 'Oil pressure sensor replacement', category: 'Engine', notes: 'Replace if faulty' },
  { name: 'Oil pump inspection', category: 'Engine', notes: 'Check pressure and operation' },
  { name: 'Oil pump replacement', category: 'Engine', notes: 'Replace if pressure low' },
  { name: 'PCV (Positive Crankcase Ventilation) valve inspection', category: 'Engine', notes: 'Check for clogging' },
  { name: 'PCV valve replacement', category: 'Engine', notes: 'Replace if clogged' },
  { name: 'Exhaust manifold inspection', category: 'Exhaust', notes: 'Check for cracks and leaks' },
  { name: 'Exhaust manifold gasket replacement', category: 'Exhaust', notes: 'Replace if leaking' },
  { name: 'Exhaust pipe inspection', category: 'Exhaust', notes: 'Check for rust and damage' },
  { name: 'Muffler inspection', category: 'Exhaust', notes: 'Check for rust and noise' },
  { name: 'Muffler replacement', category: 'Exhaust', notes: 'Replace if rusted through' },
  { name: 'Catalytic converter inspection', category: 'Exhaust', notes: 'Check for efficiency' },
  { name: 'Catalytic converter replacement', category: 'Exhaust', notes: 'Replace if clogged or failed' },
  { name: 'DPF (Diesel Particulate Filter) inspection', category: 'Exhaust', notes: 'Check for clogging' },
  { name: 'DPF cleaning', category: 'Exhaust', notes: 'Clean or regenerate' },
  { name: 'DPF replacement', category: 'Exhaust', notes: 'Replace if damaged beyond cleaning' },

  // Transmission & Drivetrain
  { name: 'Gearbox oil check', category: 'Transmission', notes: 'Check level and condition' },
  { name: 'Gearbox oil top-up', category: 'Transmission', notes: 'Top up if low' },
  { name: 'Gearbox oil change', category: 'Transmission', notes: 'Every 60,000-80,000 km' },
  { name: 'Manual transmission clutch inspection', category: 'Transmission', notes: 'Check wear and adjustment' },
  { name: 'Clutch disc inspection', category: 'Transmission', notes: 'Check for wear' },
  { name: 'Clutch disc replacement', category: 'Transmission', notes: 'Replace if worn' },
  { name: 'Clutch pressure plate inspection', category: 'Transmission', notes: 'Check for wear' },
  { name: 'Clutch pressure plate replacement', category: 'Transmission', notes: 'Replace if worn' },
  { name: 'Clutch release bearing inspection', category: 'Transmission', notes: 'Check for noise and wear' },
  { name: 'Clutch release bearing replacement', category: 'Transmission', notes: 'Replace if noisy' },
  { name: 'Flywheel inspection', category: 'Transmission', notes: 'Check for wear and hot spots' },
  { name: 'Flywheel resurfacing', category: 'Transmission', notes: 'Machine surface flat' },
  { name: 'Flywheel replacement', category: 'Transmission', notes: 'Replace if cracked' },
  { name: 'Transmission mount inspection', category: 'Transmission', notes: 'Check for wear and damage' },
  { name: 'Transmission mount replacement', category: 'Transmission', notes: 'Replace if worn' },
  { name: 'Gear linkage adjustment', category: 'Transmission', notes: 'Adjust for smooth shifting' },
  { name: 'Gear linkage lubrication', category: 'Transmission', notes: 'Lubricate linkages' },
  { name: 'Gear shifter repair', category: 'Transmission', notes: 'Repair shifter mechanism' },
  { name: 'Synchromesh gear inspection', category: 'Transmission', notes: 'Check synchro operation' },
  { name: 'Synchromesh replacement', category: 'Transmission', notes: 'Replace if worn' },
  { name: 'Torque converter inspection (automatic)', category: 'Transmission', notes: 'Check for slippage' },
  { name: 'Torque converter replacement (automatic)', category: 'Transmission', notes: 'Replace if faulty' },
  { name: 'Automatic gearbox fluid level check', category: 'Transmission', notes: 'Check fluid level' },
  { name: 'Automatic gearbox fluid replacement', category: 'Transmission', notes: 'Every 60,000 km' },
  { name: 'Automatic gearbox filter replacement', category: 'Transmission', notes: 'Replace with fluid change' },
  { name: 'Transmission cooler inspection', category: 'Transmission', notes: 'Check for leaks' },
  { name: 'Transmission cooler replacement', category: 'Transmission', notes: 'Replace if leaking' },
  { name: 'Transfer case oil inspection', category: 'Drivetrain', notes: 'Check level and condition' },
  { name: 'Transfer case oil change', category: 'Drivetrain', notes: 'Every 80,000 km' },
  { name: 'Differential oil inspection', category: 'Drivetrain', notes: 'Check level and condition' },
  { name: 'Differential oil change', category: 'Drivetrain', notes: 'Every 80,000 km' },
  { name: 'Differential bearing inspection', category: 'Drivetrain', notes: 'Check for wear' },
  { name: 'Differential bearing replacement', category: 'Drivetrain', notes: 'Replace if worn' },
  { name: 'Differential seal replacement', category: 'Drivetrain', notes: 'Replace if leaking' },
  { name: 'Driveshaft inspection', category: 'Drivetrain', notes: 'Check for balance and damage' },
  { name: 'Driveshaft balancing', category: 'Drivetrain', notes: 'Balance if vibrating' },
  { name: 'Driveshaft U-joint inspection', category: 'Drivetrain', notes: 'Check for wear' },
  { name: 'Driveshaft U-joint replacement', category: 'Drivetrain', notes: 'Replace if worn' },
  { name: 'Driveshaft CV joint inspection', category: 'Drivetrain', notes: 'Check for wear and boots' },
  { name: 'Driveshaft CV joint replacement', category: 'Drivetrain', notes: 'Replace if worn' },
  { name: 'Axle inspection', category: 'Drivetrain', notes: 'Check for damage' },
  { name: 'Axle seal replacement', category: 'Drivetrain', notes: 'Replace if leaking' },
  { name: 'Rear axle service', category: 'Drivetrain', notes: 'Service rear axle' },
  { name: 'Front axle service', category: 'Drivetrain', notes: 'Service front axle' },
  { name: 'Propeller shaft inspection', category: 'Drivetrain', notes: 'Check for damage' },
  { name: 'Propeller shaft repair', category: 'Drivetrain', notes: 'Repair as needed' },
  { name: 'Propeller shaft replacement', category: 'Drivetrain', notes: 'Replace if damaged' },
  { name: 'Wheel hub bearing inspection', category: 'Drivetrain', notes: 'Check for play and noise' },
  { name: 'Wheel hub bearing greasing', category: 'Drivetrain', notes: 'Grease bearings' },
  { name: 'Wheel hub bearing replacement', category: 'Drivetrain', notes: 'Replace if worn' },
  { name: 'Half shaft inspection', category: 'Drivetrain', notes: 'Check for damage' },
  { name: 'Half shaft oil seal replacement', category: 'Drivetrain', notes: 'Replace if leaking' },
  { name: 'Power take-off (PTO) inspection', category: 'Drivetrain', notes: 'Check operation' },
  { name: 'PTO seal replacement', category: 'Drivetrain', notes: 'Replace if leaking' },
  { name: 'PTO repair', category: 'Drivetrain', notes: 'Repair as needed' },
  { name: 'PTO replacement', category: 'Drivetrain', notes: 'Replace if faulty' },
  { name: 'Gearbox mount bushing replacement', category: 'Transmission', notes: 'Replace if worn' },
  { name: 'Transmission wiring inspection (auto gearbox)', category: 'Transmission', notes: 'Check wiring' },
  { name: 'Transmission sensor replacement', category: 'Transmission', notes: 'Replace if faulty' },

  // Suspension & Steering
  { name: 'Front suspension inspection', category: 'Suspension', notes: 'Check all components' },
  { name: 'Rear suspension inspection', category: 'Suspension', notes: 'Check all components' },
  { name: 'Leaf spring inspection', category: 'Suspension', notes: 'Check for cracks and sag' },
  { name: 'Leaf spring replacement', category: 'Suspension', notes: 'Replace if broken' },
  { name: 'Leaf spring bushing replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Leaf spring shackle inspection', category: 'Suspension', notes: 'Check for wear' },
  { name: 'Leaf spring shackle replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Coil spring inspection', category: 'Suspension', notes: 'Check for sag and cracks' },
  { name: 'Coil spring replacement', category: 'Suspension', notes: 'Replace if broken' },
  { name: 'Shock absorber inspection', category: 'Suspension', notes: 'Check for leaks and operation' },
  { name: 'Shock absorber replacement', category: 'Suspension', notes: 'Replace if leaking or worn' },
  { name: 'Strut inspection', category: 'Suspension', notes: 'Check for leaks and damage' },
  { name: 'Strut replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Stabilizer bar inspection', category: 'Suspension', notes: 'Check for damage' },
  { name: 'Stabilizer bar bushing replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Stabilizer link replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Suspension arm inspection', category: 'Suspension', notes: 'Check for wear and damage' },
  { name: 'Suspension arm bushing replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Suspension arm replacement', category: 'Suspension', notes: 'Replace if bent or worn' },
  { name: 'Kingpin inspection', category: 'Suspension', notes: 'Check for wear' },
  { name: 'Kingpin greasing', category: 'Suspension', notes: 'Grease kingpins' },
  { name: 'Kingpin replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Ball joint inspection', category: 'Suspension', notes: 'Check for play' },
  { name: 'Ball joint replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Tie rod end inspection', category: 'Steering', notes: 'Check for play' },
  { name: 'Tie rod end replacement', category: 'Steering', notes: 'Replace if worn' },
  { name: 'Drag link inspection', category: 'Steering', notes: 'Check for wear' },
  { name: 'Drag link replacement', category: 'Steering', notes: 'Replace if worn' },
  { name: 'Steering gearbox inspection', category: 'Steering', notes: 'Check for leaks and play' },
  { name: 'Steering gearbox adjustment', category: 'Steering', notes: 'Adjust for proper play' },
  { name: 'Steering gearbox replacement', category: 'Steering', notes: 'Replace if faulty' },
  { name: 'Steering pump inspection', category: 'Steering', notes: 'Check for leaks and noise' },
  { name: 'Steering pump fluid check', category: 'Steering', notes: 'Check fluid level' },
  { name: 'Steering pump fluid top-up', category: 'Steering', notes: 'Top up if low' },
  { name: 'Steering pump replacement', category: 'Steering', notes: 'Replace if faulty' },
  { name: 'Steering column inspection', category: 'Steering', notes: 'Check for play and damage' },
  { name: 'Steering column replacement', category: 'Steering', notes: 'Replace if damaged' },
  { name: 'Steering linkage lubrication', category: 'Steering', notes: 'Lubricate linkages' },
  { name: 'Wheel alignment check', category: 'Steering', notes: 'Check alignment' },
  { name: 'Wheel alignment adjustment', category: 'Steering', notes: 'Adjust alignment' },
  { name: 'Power steering hose inspection', category: 'Steering', notes: 'Check for leaks' },
  { name: 'Power steering hose replacement', category: 'Steering', notes: 'Replace if leaking' },
  { name: 'Power steering cooler inspection', category: 'Steering', notes: 'Check for leaks' },
  { name: 'Power steering cooler replacement', category: 'Steering', notes: 'Replace if leaking' },
  { name: 'Steering knuckle inspection', category: 'Steering', notes: 'Check for damage' },
  { name: 'Steering knuckle replacement', category: 'Steering', notes: 'Replace if bent' },
  { name: 'Suspension airbag inspection (for air suspension)', category: 'Suspension', notes: 'Check for leaks' },
  { name: 'Suspension airbag replacement', category: 'Suspension', notes: 'Replace if leaking' },
  { name: 'Air suspension compressor inspection', category: 'Suspension', notes: 'Check operation' },
  { name: 'Air suspension compressor replacement', category: 'Suspension', notes: 'Replace if faulty' },
  { name: 'Air suspension valve inspection', category: 'Suspension', notes: 'Check for leaks' },
  { name: 'Air suspension valve replacement', category: 'Suspension', notes: 'Replace if leaking' },
  { name: 'Ride height sensor inspection', category: 'Suspension', notes: 'Check operation' },
  { name: 'Ride height sensor replacement', category: 'Suspension', notes: 'Replace if faulty' },
  { name: 'Control arm inspection', category: 'Suspension', notes: 'Check for wear' },
  { name: 'Control arm replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Control arm bushing replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Subframe inspection', category: 'Suspension', notes: 'Check for damage' },
  { name: 'Subframe bushing replacement', category: 'Suspension', notes: 'Replace if worn' },
  { name: 'Steering rack inspection', category: 'Steering', notes: 'Check for play and leaks' },
  { name: 'Steering rack boot replacement', category: 'Steering', notes: 'Replace if torn' },
  { name: 'Steering rack replacement', category: 'Steering', notes: 'Replace if faulty' },
  { name: 'Pitman arm inspection', category: 'Steering', notes: 'Check for wear' },
  { name: 'Pitman arm replacement', category: 'Steering', notes: 'Replace if worn' },
  { name: 'Idler arm inspection', category: 'Steering', notes: 'Check for wear' },
  { name: 'Idler arm replacement', category: 'Steering', notes: 'Replace if worn' },

  // Brakes & Air System
  { name: 'Brake pad inspection', category: 'Brakes', notes: 'Check thickness' },
  { name: 'Brake pad replacement', category: 'Brakes', notes: 'Replace if worn below minimum' },
  { name: 'Brake shoe inspection', category: 'Brakes', notes: 'Check lining thickness' },
  { name: 'Brake shoe replacement', category: 'Brakes', notes: 'Replace if worn' },
  { name: 'Brake disc (rotor) inspection', category: 'Brakes', notes: 'Check for wear and scoring' },
  { name: 'Brake disc resurfacing', category: 'Brakes', notes: 'Machine if warped or scored' },
  { name: 'Brake disc replacement', category: 'Brakes', notes: 'Replace if below minimum thickness' },
  { name: 'Brake drum inspection', category: 'Brakes', notes: 'Check for wear and scoring' },
  { name: 'Brake drum replacement', category: 'Brakes', notes: 'Replace if worn' },
  { name: 'Brake caliper inspection', category: 'Brakes', notes: 'Check for leaks and operation' },
  { name: 'Brake caliper repair kit installation', category: 'Brakes', notes: 'Replace seals and boots' },
  { name: 'Brake caliper replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Brake hose inspection', category: 'Brakes', notes: 'Check for cracks and bulges' },
  { name: 'Brake hose replacement', category: 'Brakes', notes: 'Replace if damaged' },
  { name: 'Brake pipe inspection', category: 'Brakes', notes: 'Check for rust and leaks' },
  { name: 'Brake pipe replacement', category: 'Brakes', notes: 'Replace if rusted or leaking' },
  { name: 'Brake master cylinder inspection', category: 'Brakes', notes: 'Check for leaks and operation' },
  { name: 'Brake master cylinder replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Brake booster inspection', category: 'Brakes', notes: 'Check for operation' },
  { name: 'Brake booster replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'ABS sensor inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'ABS sensor replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'ABS control module inspection', category: 'Brakes', notes: 'Check for fault codes' },
  { name: 'ABS control module replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Parking brake cable inspection', category: 'Brakes', notes: 'Check for operation' },
  { name: 'Parking brake cable replacement', category: 'Brakes', notes: 'Replace if seized' },
  { name: 'Parking brake adjustment', category: 'Brakes', notes: 'Adjust for proper operation' },
  { name: 'Brake fluid level check', category: 'Brakes', notes: 'Check fluid level' },
  { name: 'Brake fluid top-up', category: 'Brakes', notes: 'Top up if low' },
  { name: 'Brake fluid flush & replacement', category: 'Brakes', notes: 'Every 2 years or 40,000 km' },
  { name: 'Brake pedal inspection', category: 'Brakes', notes: 'Check for proper feel' },
  { name: 'Brake pedal linkage adjustment', category: 'Brakes', notes: 'Adjust as needed' },
  { name: 'Brake warning light diagnosis', category: 'Brakes', notes: 'Diagnose warning light' },
  { name: 'Brake chamber inspection (air brake)', category: 'Brakes', notes: 'Check for operation' },
  { name: 'Brake chamber diaphragm replacement', category: 'Brakes', notes: 'Replace if torn' },
  { name: 'Brake chamber replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Slack adjuster inspection', category: 'Brakes', notes: 'Check adjustment' },
  { name: 'Slack adjuster adjustment', category: 'Brakes', notes: 'Adjust proper stroke' },
  { name: 'Slack adjuster replacement', category: 'Brakes', notes: 'Replace if worn' },
  { name: 'Air compressor inspection', category: 'Brakes', notes: 'Check operation and output' },
  { name: 'Air compressor replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Air dryer inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Air dryer filter replacement', category: 'Brakes', notes: 'Replace filter element' },
  { name: 'Air dryer replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Air tank drain (manual/automatic)', category: 'Brakes', notes: 'Drain accumulated moisture' },
  { name: 'Air tank replacement', category: 'Brakes', notes: 'Replace if rusted' },
  { name: 'Brake relay valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Brake relay valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Foot brake valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Foot brake valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Hand brake (park brake) valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Hand brake valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Quick release valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Quick release valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Check valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Check valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Load sensing valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Load sensing valve adjustment', category: 'Brakes', notes: 'Adjust as needed' },
  { name: 'Load sensing valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Proportioning valve inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Proportioning valve replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Emergency brake system inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Emergency brake release procedure', category: 'Brakes', notes: 'Release emergency brakes' },
  { name: 'Brake lining inspection', category: 'Brakes', notes: 'Check lining thickness' },
  { name: 'Brake lining replacement', category: 'Brakes', notes: 'Replace if worn' },
  { name: 'Low air pressure warning system inspection', category: 'Brakes', notes: 'Check operation' },
  { name: 'Low air buzzer replacement', category: 'Brakes', notes: 'Replace if faulty' },
  { name: 'Brake balance testing (dyno)', category: 'Brakes', notes: 'Test brake balance' },
  { name: 'Full brake performance test', category: 'Brakes', notes: 'Comprehensive brake test' },

  // Wheels & Tires
  { name: 'Tire pressure check', category: 'Tires', notes: 'Check and adjust pressure' },
  { name: 'Tire inflation (adjust to recommended PSI)', category: 'Tires', notes: 'Inflate to proper pressure' },
  { name: 'Tire rotation (front to rear, cross)', category: 'Tires', notes: 'Rotate tires for even wear' },
  { name: 'Tire balancing', category: 'Tires', notes: 'Balance wheels' },
  { name: 'Wheel alignment check', category: 'Tires', notes: 'Check alignment' },
  { name: 'Wheel alignment adjustment', category: 'Tires', notes: 'Adjust alignment' },
  { name: 'Tire tread depth inspection', category: 'Tires', notes: 'Check tread depth' },
  { name: 'Tire sidewall inspection', category: 'Tires', notes: 'Check for damage' },
  { name: 'Tire replacement (single)', category: 'Tires', notes: 'Replace single tire' },
  { name: 'Tire replacement (dual set)', category: 'Tires', notes: 'Replace dual tires' },
  { name: 'Emergency roadside tire change', category: 'Tires', notes: 'Change tire on roadside' },
  { name: 'Spare tire inspection', category: 'Tires', notes: 'Check spare tire condition' },
  { name: 'Spare tire inflation', category: 'Tires', notes: 'Inflate spare tire' },
  { name: 'Spare tire replacement', category: 'Tires', notes: 'Replace spare tire' },
  { name: 'Wheel nut torque check', category: 'Tires', notes: 'Check wheel nut torque' },
  { name: 'Wheel nut retightening', category: 'Tires', notes: 'Retighten wheel nuts' },
  { name: 'Wheel stud inspection', category: 'Tires', notes: 'Check for damage' },
  { name: 'Wheel stud replacement', category: 'Tires', notes: 'Replace if damaged' },
  { name: 'Wheel nut replacement', category: 'Tires', notes: 'Replace if damaged' },
  { name: 'Wheel rim inspection', category: 'Tires', notes: 'Check for damage' },
  { name: 'Wheel rim straightening', category: 'Tires', notes: 'Straighten bent rim' },
  { name: 'Wheel rim replacement', category: 'Tires', notes: 'Replace if damaged' },
  { name: 'Hub cap inspection', category: 'Tires', notes: 'Check hub caps' },
  { name: 'Hub cap replacement', category: 'Tires', notes: 'Replace if damaged' },
  { name: 'Wheel bearing inspection', category: 'Tires', notes: 'Check for play' },
  { name: 'Wheel bearing greasing', category: 'Tires', notes: 'Grease bearings' },
  { name: 'Wheel bearing replacement', category: 'Tires', notes: 'Replace if worn' },
  { name: 'Tire puncture inspection', category: 'Tires', notes: 'Inspect puncture' },
  { name: 'Tire puncture repair (plug/patch)', category: 'Tires', notes: 'Repair puncture' },
  { name: 'Tube replacement (if tube type tire)', category: 'Tires', notes: 'Replace inner tube' },
  { name: 'Valve stem inspection', category: 'Tires', notes: 'Check valve stem' },
  { name: 'Valve stem replacement', category: 'Tires', notes: 'Replace if leaking' },
  { name: 'Tire bead reseating', category: 'Tires', notes: 'Reseat tire bead' },
  { name: 'Tire blowout roadside service', category: 'Tires', notes: 'Service blowout on roadside' },
  { name: 'Rim crack welding repair', category: 'Tires', notes: 'Weld rim cracks' },
  { name: 'Hub oil seal inspection', category: 'Tires', notes: 'Check for leaks' },
  { name: 'Hub oil seal replacement', category: 'Tires', notes: 'Replace if leaking' },
  { name: 'Hub greasing service', category: 'Tires', notes: 'Grease wheel hubs' },
  { name: 'Tire rotation for trailer axles', category: 'Tires', notes: 'Rotate trailer tires' },
  { name: 'Dual tire spacing inspection', category: 'Tires', notes: 'Check dual tire spacing' },
  { name: 'Tire cupping/wear pattern diagnosis', category: 'Tires', notes: 'Diagnose wear patterns' },
  { name: 'Seasonal tire change (summer/winter)', category: 'Tires', notes: 'Change seasonal tires' },
  { name: 'Load rating compliance check', category: 'Tires', notes: 'Check load rating' },
  { name: 'Tire pressure monitoring system (TPMS) sensor inspection', category: 'Tires', notes: 'Check TPMS sensors' },
  { name: 'TPMS sensor replacement', category: 'Tires', notes: 'Replace faulty sensors' },
  { name: 'TPMS calibration', category: 'Tires', notes: 'Calibrate TPMS system' },
  { name: 'Wheel run-out inspection', category: 'Tires', notes: 'Check wheel run-out' },
  { name: 'Rim paint/refinishing', category: 'Tires', notes: 'Refinish wheel rims' },
  { name: 'Wheel balancing weights replacement', category: 'Tires', notes: 'Replace balance weights' },

  // Trailer & Flatbed / Lowbed
  { name: 'Trailer chassis inspection', category: 'Trailer', notes: 'Check for cracks and damage' },
  { name: 'Trailer chassis crack welding', category: 'Trailer', notes: 'Weld chassis cracks' },
  { name: 'Trailer chassis reinforcement', category: 'Trailer', notes: 'Reinforce chassis' },
  { name: 'Trailer kingpin inspection', category: 'Trailer Coupling', notes: 'Check kingpin wear' },
  { name: 'Trailer kingpin replacement', category: 'Trailer Coupling', notes: 'Replace if worn' },
  { name: 'Fifth wheel inspection', category: 'Trailer Coupling', notes: 'Check fifth wheel' },
  { name: 'Fifth wheel greasing', category: 'Trailer Coupling', notes: 'Grease fifth wheel' },
  { name: 'Fifth wheel adjustment', category: 'Trailer Coupling', notes: 'Adjust fifth wheel' },
  { name: 'Fifth wheel replacement', category: 'Trailer Coupling', notes: 'Replace if damaged' },
  { name: 'Landing gear inspection', category: 'Trailer', notes: 'Check landing gear' },
  { name: 'Landing gear lubrication', category: 'Trailer', notes: 'Lubricate landing gear' },
  { name: 'Landing gear repair', category: 'Trailer', notes: 'Repair landing gear' },
  { name: 'Landing gear replacement', category: 'Trailer', notes: 'Replace if faulty' },
  { name: 'Trailer frame straightening', category: 'Trailer', notes: 'Straighten frame' },
  { name: 'Trailer cross-member welding', category: 'Trailer', notes: 'Weld cross-members' },
  { name: 'Trailer floorboard inspection', category: 'Trailer Body', notes: 'Check floor condition' },
  { name: 'Trailer floorboard replacement', category: 'Trailer Body', notes: 'Replace damaged floor' },
  { name: 'Trailer flooring welding repair', category: 'Trailer Body', notes: 'Weld floor repairs' },
  { name: 'Trailer sidewall inspection', category: 'Trailer Body', notes: 'Check sidewalls' },
  { name: 'Trailer sidewall replacement', category: 'Trailer Body', notes: 'Replace sidewalls' },
  { name: 'Trailer sidewall welding repair', category: 'Trailer Body', notes: 'Weld sidewall repairs' },
  { name: 'Trailer roof inspection', category: 'Trailer Body', notes: 'Check roof condition' },
  { name: 'Trailer roof panel replacement', category: 'Trailer Body', notes: 'Replace roof panels' },
  { name: 'Trailer curtain replacement (for curtain trailers)', category: 'Trailer Body', notes: 'Replace side curtains' },
  { name: 'Trailer body painting', category: 'Trailer Body', notes: 'Paint trailer body' },
  { name: 'Trailer body panel repair', category: 'Trailer Body', notes: 'Repair body panels' },
  { name: 'Trailer tailgate inspection', category: 'Trailer Body', notes: 'Check tailgate' },
  { name: 'Trailer tailgate welding repair', category: 'Trailer Body', notes: 'Weld tailgate repairs' },
  { name: 'Trailer tailgate replacement', category: 'Trailer Body', notes: 'Replace tailgate' },
  { name: 'Trailer ramp inspection', category: 'Trailer Body', notes: 'Check ramps' },
  { name: 'Trailer ramp repair', category: 'Trailer Body', notes: 'Repair ramps' },
  { name: 'Trailer ramp replacement', category: 'Trailer Body', notes: 'Replace ramps' },
  { name: 'Flatbed deck inspection', category: 'Trailer Body', notes: 'Check deck condition' },
  { name: 'Flatbed deck replacement', category: 'Trailer Body', notes: 'Replace deck' },
  { name: 'Flatbed deck welding repair', category: 'Trailer Body', notes: 'Weld deck repairs' },
  { name: 'Flatbed stake pocket repair', category: 'Trailer Body', notes: 'Repair stake pockets' },
  { name: 'Flatbed side rail inspection', category: 'Trailer Body', notes: 'Check side rails' },
  { name: 'Flatbed side rail welding', category: 'Trailer Body', notes: 'Weld side rails' },
  { name: 'Flatbed extension fitting (2XL/3XL)', category: 'Trailer Body', notes: 'Install extensions' },
  { name: 'Lowbed gooseneck inspection', category: 'Trailer', notes: 'Check gooseneck' },
  { name: 'Lowbed gooseneck welding repair', category: 'Trailer', notes: 'Weld gooseneck repairs' },
  { name: 'Lowbed hydraulic gooseneck repair', category: 'Trailer', notes: 'Repair hydraulic gooseneck' },
  { name: 'Lowbed deck panel replacement', category: 'Trailer Body', notes: 'Replace deck panels' },
  { name: 'Lowbed deck reinforcement', category: 'Trailer Body', notes: 'Reinforce deck' },
  { name: 'Trailer suspension inspection', category: 'Suspension', notes: 'Check suspension' },
  { name: 'Trailer suspension bushing replacement', category: 'Suspension', notes: 'Replace bushings' },
  { name: 'Trailer suspension welding repair', category: 'Suspension', notes: 'Weld suspension repairs' },
  { name: 'Trailer axle inspection', category: 'Drivetrain', notes: 'Check axles' },
  { name: 'Trailer axle replacement', category: 'Drivetrain', notes: 'Replace axles' },
  { name: 'Trailer hub inspection', category: 'Tires', notes: 'Check hubs' },
  { name: 'Trailer hub oil change', category: 'Tires', notes: 'Change hub oil' },
  { name: 'Trailer hub seal replacement', category: 'Tires', notes: 'Replace hub seals' },
  { name: 'Trailer wheel bearing greasing', category: 'Tires', notes: 'Grease wheel bearings' },
  { name: 'Trailer wheel bearing replacement', category: 'Tires', notes: 'Replace wheel bearings' },
  { name: 'Trailer brake inspection', category: 'Brakes', notes: 'Check brakes' },
  { name: 'Trailer brake shoe replacement', category: 'Brakes', notes: 'Replace brake shoes' },
  { name: 'Trailer brake drum replacement', category: 'Brakes', notes: 'Replace brake drums' },
  { name: 'Trailer brake chamber replacement', category: 'Brakes', notes: 'Replace brake chambers' },
  { name: 'Trailer slack adjuster adjustment', category: 'Brakes', notes: 'Adjust slack adjusters' },
  { name: 'Trailer air tank inspection', category: 'Brakes', notes: 'Check air tanks' },
  { name: 'Trailer air tank replacement', category: 'Brakes', notes: 'Replace air tanks' },
  { name: 'Trailer air pipe inspection', category: 'Brakes', notes: 'Check air lines' },
  { name: 'Trailer air pipe replacement', category: 'Brakes', notes: 'Replace air lines' },
  { name: 'Trailer electrical wiring inspection', category: 'Electrical', notes: 'Check wiring' },
  { name: 'Trailer wiring harness replacement', category: 'Electrical', notes: 'Replace wiring harness' },
  { name: 'Trailer light inspection', category: 'Electrical', notes: 'Check lights' },
  { name: 'Trailer light bulb replacement', category: 'Electrical', notes: 'Replace bulbs' },
  { name: 'Trailer tail lamp assembly replacement', category: 'Electrical', notes: 'Replace tail lamps' },
  { name: 'Trailer marker light replacement', category: 'Electrical', notes: 'Replace marker lights' },
  { name: 'Trailer ABS wiring inspection', category: 'Brakes', notes: 'Check ABS wiring' },
  { name: 'Trailer ABS ECU replacement', category: 'Brakes', notes: 'Replace ABS ECU' },
  { name: 'Trailer side reflector replacement', category: 'Electrical', notes: 'Replace reflectors' },
  { name: 'Trailer registration plate bracket replacement', category: 'Trailer Body', notes: 'Replace plate bracket' },
  { name: 'Trailer safety chain inspection', category: 'Trailer', notes: 'Check safety chains' },
  { name: 'Trailer safety chain replacement', category: 'Trailer', notes: 'Replace safety chains' },
  { name: 'Trailer load securing point inspection', category: 'Trailer', notes: 'Check securing points' },
  { name: 'Trailer load securing point welding', category: 'Trailer', notes: 'Weld securing points' },
  { name: 'Trailer hydraulic line inspection (for hydraulic trailers)', category: 'Hydraulics', notes: 'Check hydraulic lines' },
  { name: 'Trailer hydraulic cylinder inspection', category: 'Hydraulics', notes: 'Check hydraulic cylinders' },
  { name: 'Trailer hydraulic cylinder replacement', category: 'Hydraulics', notes: 'Replace hydraulic cylinders' },
  { name: 'Trailer painting & anti-rust treatment', category: 'Trailer Body', notes: 'Paint and treat rust' },

  // Welding & Fabrication
  { name: 'Chassis welding repair', category: 'Welding', notes: 'Weld chassis repairs' },
  { name: 'Chassis reinforcement welding', category: 'Welding', notes: 'Weld reinforcements' },
  { name: 'Frame crack welding', category: 'Welding', notes: 'Weld frame cracks' },
  { name: 'Trailer cross-member welding', category: 'Welding', notes: 'Weld cross-members' },
  { name: 'Flatbed deck welding', category: 'Welding', notes: 'Weld deck repairs' },
  { name: 'Lowbed deck welding', category: 'Welding', notes: 'Weld lowbed repairs' },
  { name: 'Stake pocket welding', category: 'Welding', notes: 'Weld stake pockets' },
  { name: 'Side rail welding', category: 'Welding', notes: 'Weld side rails' },
  { name: 'Ramp welding repair', category: 'Welding', notes: 'Weld ramp repairs' },
  { name: 'Tailgate welding repair', category: 'Welding', notes: 'Weld tailgate repairs' },
  { name: 'Exhaust pipe welding repair', category: 'Welding', notes: 'Weld exhaust repairs' },
  { name: 'Exhaust manifold welding repair', category: 'Welding', notes: 'Weld manifold repairs' },
  { name: 'Mounting bracket welding', category: 'Welding', notes: 'Weld brackets' },
  { name: 'Suspension bracket welding', category: 'Welding', notes: 'Weld suspension brackets' },
  { name: 'Engine mount welding repair', category: 'Welding', notes: 'Weld engine mounts' },
  { name: 'PTO mount welding', category: 'Welding', notes: 'Weld PTO mounts' },
  { name: 'Hitch mount welding', category: 'Welding', notes: 'Weld hitch mounts' },
  { name: 'Toolbox mount welding', category: 'Welding', notes: 'Weld toolbox mounts' },
  { name: 'Fuel tank mount welding', category: 'Welding', notes: 'Weld fuel tank mounts' },
  { name: 'Hydraulic cylinder mount welding', category: 'Welding', notes: 'Weld hydraulic mounts' },
  { name: 'Welding of broken clevis', category: 'Welding', notes: 'Weld clevis repairs' },
  { name: 'Welding of broken hanger', category: 'Welding', notes: 'Weld hanger repairs' },
  { name: 'Welding of trailer support brackets', category: 'Welding', notes: 'Weld support brackets' },
  { name: 'Welding of trailer guard rails', category: 'Welding', notes: 'Weld guard rails' },
  { name: 'Welding of crane mounts', category: 'Welding', notes: 'Weld crane mounts' },
  { name: 'Welding of winch mounts', category: 'Welding', notes: 'Weld winch mounts' },
  { name: 'Welding of bumper mounts', category: 'Welding', notes: 'Weld bumper mounts' },
  { name: 'Welding of guard brackets', category: 'Welding', notes: 'Weld guard brackets' },
  { name: 'Welding for custom attachments', category: 'Welding', notes: 'Weld custom attachments' },
  { name: 'Welding repair of welded joints', category: 'Welding', notes: 'Repair welded joints' },
  { name: 'Welding inspection', category: 'Welding', notes: 'Inspect welds' },
  { name: 'Welding maintenance', category: 'Welding', notes: 'Maintain welding equipment' },
  { name: 'Welding rod replacement', category: 'Welding', notes: 'Replace welding rods' },
  { name: 'Welding equipment inspection', category: 'Welding', notes: 'Inspect equipment' },
  { name: 'Welding machine calibration', category: 'Welding', notes: 'Calibrate welding machines' },
  { name: 'TIG/MIG welding task', category: 'Welding', notes: 'TIG/MIG welding' },
  { name: 'Arc welding task', category: 'Welding', notes: 'Arc welding' },
  { name: 'Spot welding task', category: 'Welding', notes: 'Spot welding' },
  { name: 'Metal fabrication for custom parts', category: 'Welding', notes: 'Fabricate custom parts' },

  // Cabin & Interior
  { name: 'Driver seat inspection', category: 'Interior', notes: 'Check seat condition' },
  { name: 'Driver seat adjustment', category: 'Interior', notes: 'Adjust seat position' },
  { name: 'Passenger seat inspection', category: 'Interior', notes: 'Check passenger seat' },
  { name: 'Passenger seat adjustment', category: 'Interior', notes: 'Adjust passenger seat' },
  { name: 'Seatbelt inspection', category: 'Interior', notes: 'Check seatbelt condition' },
  { name: 'Seatbelt replacement', category: 'Interior', notes: 'Replace if damaged' },
  { name: 'HVAC system inspection', category: 'HVAC', notes: 'Check HVAC operation' },
  { name: 'HVAC filter replacement', category: 'HVAC', notes: 'Replace cabin filter' },
  { name: 'HVAC blower motor check', category: 'HVAC', notes: 'Check blower motor' },
  { name: 'Dashboard lights inspection', category: 'Electrical', notes: 'Check dashboard lights' },
  { name: 'Dashboard gauge calibration', category: 'Electrical', notes: 'Calibrate gauges' },
  { name: 'Steering wheel inspection', category: 'Interior', notes: 'Check steering wheel' },
  { name: 'Steering wheel adjustment', category: 'Interior', notes: 'Adjust steering wheel' },
  { name: 'Steering column inspection', category: 'Steering', notes: 'Check steering column' },
  { name: 'Window operation inspection', category: 'Interior', notes: 'Check window operation' },
  { name: 'Window regulator replacement', category: 'Interior', notes: 'Replace window regulators' },
  { name: 'Door lock inspection', category: 'Interior', notes: 'Check door locks' },
  { name: 'Door lock actuator replacement', category: 'Interior', notes: 'Replace lock actuators' },
  { name: 'Mirror inspection', category: 'Interior', notes: 'Check mirrors' },
  { name: 'Mirror replacement', category: 'Interior', notes: 'Replace if damaged' },
  { name: 'Sun visor inspection', category: 'Interior', notes: 'Check sun visors' },
  { name: 'Sun visor replacement', category: 'Interior', notes: 'Replace if damaged' },
  { name: 'Cabin floor mat replacement', category: 'Interior', notes: 'Replace floor mats' },
  { name: 'Cabin interior lighting inspection', category: 'Electrical', notes: 'Check interior lights' },
  { name: 'Cabin interior lighting replacement', category: 'Electrical', notes: 'Replace bulbs' },
  { name: 'Roof lining inspection', category: 'Interior', notes: 'Check headliner' },
  { name: 'Roof lining repair', category: 'Interior', notes: 'Repair headliner' },
  { name: 'Glove box inspection', category: 'Interior', notes: 'Check glove box' },
  { name: 'Glove box repair', category: 'Interior', notes: 'Repair glove box' },
  { name: 'Horn operation check', category: 'Electrical', notes: 'Check horn operation' },
  { name: 'Wiper motor inspection', category: 'Electrical', notes: 'Check wiper motor' },
  { name: 'Wiper blade replacement', category: 'Electrical', notes: 'Replace wiper blades' },
  { name: 'Cabin door seal inspection', category: 'Interior', notes: 'Check door seals' },
  { name: 'Cabin door seal replacement', category: 'Interior', notes: 'Replace door seals' },
  { name: 'Fire extinguisher mount inspection', category: 'Safety', notes: 'Check extinguisher mount' },

  // Safety & Electrical
  { name: 'Fire extinguisher inspection', category: 'Safety', notes: 'Check extinguisher' },
  { name: 'Fire extinguisher replacement', category: 'Safety', notes: 'Replace if expired' },
  { name: 'First aid kit check', category: 'Safety', notes: 'Check first aid kit' },
  { name: 'Seatbelt inspection', category: 'Safety', notes: 'Check seatbelts' },
  { name: 'Seatbelt replacement', category: 'Safety', notes: 'Replace if damaged' },
  { name: 'Reflector inspection', category: 'Safety', notes: 'Check reflectors' },
  { name: 'Reflector replacement', category: 'Safety', notes: 'Replace if damaged' },
  { name: 'Warning triangle inspection', category: 'Safety', notes: 'Check warning triangle' },
  { name: 'Warning triangle replacement', category: 'Safety', notes: 'Replace if damaged' },
  { name: 'Headlight inspection', category: 'Electrical', notes: 'Check headlights' },
  { name: 'Headlight bulb replacement', category: 'Electrical', notes: 'Replace headlight bulbs' },
  { name: 'Tail light inspection', category: 'Electrical', notes: 'Check tail lights' },
  { name: 'Tail light bulb replacement', category: 'Electrical', notes: 'Replace tail light bulbs' },
  { name: 'Brake light inspection', category: 'Electrical', notes: 'Check brake lights' },
  { name: 'Brake light bulb replacement', category: 'Electrical', notes: 'Replace brake light bulbs' },
  { name: 'Indicator light inspection', category: 'Electrical', notes: 'Check indicators' },
  { name: 'Indicator light bulb replacement', category: 'Electrical', notes: 'Replace indicator bulbs' },
  { name: 'Hazard light inspection', category: 'Electrical', notes: 'Check hazard lights' },
  { name: 'Hazard light bulb replacement', category: 'Electrical', notes: 'Replace hazard bulbs' },
  { name: 'Dashboard warning light check', category: 'Electrical', notes: 'Check warning lights' },
  { name: 'ABS sensor inspection', category: 'Electrical', notes: 'Check ABS sensors' },
  { name: 'ABS sensor replacement', category: 'Electrical', notes: 'Replace ABS sensors' },
  { name: 'ABS module inspection', category: 'Electrical', notes: 'Check ABS module' },
  { name: 'ABS module replacement', category: 'Electrical', notes: 'Replace ABS module' },
  { name: 'Battery voltage check', category: 'Electrical', notes: 'Check battery voltage' },
  { name: 'Battery replacement', category: 'Electrical', notes: 'Replace battery' },
  { name: 'Battery terminal cleaning', category: 'Electrical', notes: 'Clean battery terminals' },
  { name: 'Battery charging system check', category: 'Electrical', notes: 'Check charging system' },
  { name: 'Alternator inspection', category: 'Electrical', notes: 'Check alternator' },
  { name: 'Alternator replacement', category: 'Electrical', notes: 'Replace alternator' },
  { name: 'Starter motor inspection', category: 'Electrical', notes: 'Check starter motor' },
  { name: 'Starter motor replacement', category: 'Electrical', notes: 'Replace starter motor' },
  { name: 'Fuse inspection', category: 'Electrical', notes: 'Check fuses' },
  { name: 'Fuse replacement', category: 'Electrical', notes: 'Replace blown fuses' },
  { name: 'Wiring harness inspection', category: 'Electrical', notes: 'Check wiring harness' },
  { name: 'Wiring harness repair', category: 'Electrical', notes: 'Repair wiring harness' },
  { name: 'Relay inspection', category: 'Electrical', notes: 'Check relays' },
  { name: 'Relay replacement', category: 'Electrical', notes: 'Replace relays' },
  { name: 'Horn inspection', category: 'Electrical', notes: 'Check horn' },
  { name: 'Horn replacement', category: 'Electrical', notes: 'Replace horn' },
  { name: 'Reverse buzzer inspection', category: 'Electrical', notes: 'Check reverse buzzer' },
  { name: 'Reverse buzzer replacement', category: 'Electrical', notes: 'Replace reverse buzzer' },
  { name: 'Trailer electrical connector inspection', category: 'Electrical', notes: 'Check trailer connector' },
  { name: 'Trailer electrical connector cleaning', category: 'Electrical', notes: 'Clean trailer connector' },
  { name: 'Trailer electrical connector replacement', category: 'Electrical', notes: 'Replace trailer connector' },

  // General Maintenance, Diagnostics & Puncture
  { name: 'Greasing points lubrication', category: 'General', notes: 'Lubricate all grease points' },
  { name: 'Truck wash', category: 'General', notes: 'Wash truck exterior' },
  { name: 'Anti-rust treatment', category: 'General', notes: 'Apply anti-rust treatment' },
  { name: 'Paint touch-up', category: 'General', notes: 'Touch up paint chips' },
  { name: 'Inspection of lights', category: 'General', notes: 'Inspect all lights' },
  { name: 'Battery check', category: 'General', notes: 'Check battery condition' },
  { name: 'Fluid levels inspection (oil, coolant, brake, steering, washer)', category: 'General', notes: 'Check all fluid levels' },
  { name: 'Fuel system inspection', category: 'General', notes: 'Inspect fuel system' },
  { name: 'Engine belts inspection', category: 'General', notes: 'Inspect engine belts' },
  { name: 'Engine belts replacement', category: 'General', notes: 'Replace worn belts' },
  { name: 'Engine hoses inspection', category: 'General', notes: 'Inspect engine hoses' },
  { name: 'Engine hoses replacement', category: 'General', notes: 'Replace damaged hoses' },
  { name: 'Air filter inspection', category: 'General', notes: 'Inspect air filter' },
  { name: 'Air filter replacement', category: 'General', notes: 'Replace air filter' },
  { name: 'Coolant level check', category: 'General', notes: 'Check coolant level' },
  { name: 'Coolant refill', category: 'General', notes: 'Refill coolant' },
  { name: 'Radiator pressure testing', category: 'General', notes: 'Pressure test radiator' },
  { name: 'Turbocharger system check', category: 'General', notes: 'Check turbo system' },
  { name: 'Fuel injector cleaning', category: 'General', notes: 'Clean fuel injectors' },
  { name: 'Fuel injector replacement', category: 'General', notes: 'Replace fuel injectors' },
  { name: 'Transmission fluid check', category: 'General', notes: 'Check transmission fluid' },
  { name: 'Transmission filter replacement', category: 'General', notes: 'Replace transmission filter' },
  { name: 'Differential oil check', category: 'General', notes: 'Check differential oil' },
  { name: 'Differential oil replacement', category: 'General', notes: 'Replace differential oil' },
  { name: 'Brake fluid flush', category: 'General', notes: 'Flush brake fluid' },
  { name: 'Brake system inspection', category: 'General', notes: 'Inspect brake system' },
  { name: 'Puncture repair', category: 'General', notes: 'Repair tire punctures' },
  { name: 'Tire patching', category: 'General', notes: 'Patch tires' },
  { name: 'Tire balancing', category: 'General', notes: 'Balance tires' },
  { name: 'Wheel alignment', category: 'General', notes: 'Align wheels' },
  { name: 'Computer diagnostics / fault code scanning', category: 'General', notes: 'Scan for fault codes' },
  { name: 'Preventive maintenance checklist completion', category: 'Preventive', notes: 'Complete PM checklist' },
  { name: 'Record keeping & reporting', category: 'General', notes: 'Maintain records' },
  { name: 'Lubrication of hinges & locks', category: 'General', notes: 'Lubricate hinges and locks' },
  { name: 'Door check & hinge lubrication', category: 'General', notes: 'Lubricate door hinges' },
  { name: 'Hydraulic system inspection', category: 'Hydraulics', notes: 'Inspect hydraulic system' },
  { name: 'Hydraulic fluid refill', category: 'Hydraulics', notes: 'Refill hydraulic fluid' },
  { name: 'Preventive vibration analysis', category: 'Preventive', notes: 'Analyze vibrations' },
  { name: 'Cooling fan clutch inspection', category: 'Cooling', notes: 'Inspect fan clutch' },
  { name: 'PTO coupling inspection & lubrication', category: 'Drivetrain', notes: 'Inspect and lubricate PTO' },
  { name: 'Air suspension compressor check', category: 'Suspension', notes: 'Check air compressor' },
  { name: 'Air suspension valve inspection', category: 'Suspension', notes: 'Inspect air valves' },
  { name: 'Load sensor inspection', category: 'General', notes: 'Inspect load sensors' },
  { name: 'Seasonal maintenance inspection', category: 'Preventive', notes: 'Seasonal inspection' },
  { name: 'Engine oil sampling', category: 'Preventive', notes: 'Sample engine oil' },
  { name: 'Engine oil analysis', category: 'Preventive', notes: 'Analyze engine oil' },
  { name: 'Fluid leak detection', category: 'General', notes: 'Detect fluid leaks' },
  { name: 'Cabin air conditioning cleaning & refill', category: 'HVAC', notes: 'Clean and refill A/C' }
]

async function main() {
  console.log('Populating maintenance jobs...')

  try {
    // Clear existing jobs (optional - comment out if you want to keep existing jobs)
    console.log('Clearing existing maintenance jobs...')
    await prisma.maintenanceJob.deleteMany()
    console.log('Existing jobs cleared.')

    // Insert new maintenance jobs using upsert to handle duplicates
    console.log('Inserting maintenance jobs...')
    const createdJobs = await Promise.all(
      maintenanceJobs.map(async (job) => {
        return await prisma.maintenanceJob.upsert({
          where: {
            name_category: {
              name: job.name,
              category: job.category
            }
          },
          update: {
            parts: job.parts || null,
            notes: job.notes || null,
            isActive: true
          },
          create: {
            name: job.name,
            category: job.category,
            parts: job.parts || null,
            notes: job.notes || null,
            isActive: true
          }
        })
      })
    )

    console.log(`Successfully created ${createdJobs.length} maintenance jobs!`)

    // Log categories created
    const categories = Array.from(new Set(maintenanceJobs.map(job => job.category)))
    console.log(`\nCategories created (${categories.length}):`)
    categories.forEach(category => {
      const jobCount = maintenanceJobs.filter(job => job.category === category).length
      console.log(`  - ${category}: ${jobCount} jobs`)
    })

    // Log some sample jobs
    console.log('\nSample jobs created:')
    createdJobs.slice(0, 10).forEach(job => {
      console.log(`  - ${job.name} (${job.category})`)
    })

    console.log('\nMaintenance jobs population completed successfully!')

  } catch (error) {
    console.error('Error populating maintenance jobs:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })